In [1]:
import pandas as pd
import numpy as np

In [2]:
%pip install requests

Requirement already satisfied: requests in d:\code\plot_env\Lib\site-packages (2.32.5)
Requirement already satisfied: charset_normalizer<4,>=2 in d:\code\plot_env\Lib\site-packages (from requests) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in d:\code\plot_env\Lib\site-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\code\plot_env\Lib\site-packages (from requests) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in d:\code\plot_env\Lib\site-packages (from requests) (2026.2.25)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import requests
from io import StringIO

In [4]:
import requests
import pandas as pd
from io import StringIO

# Raw URL ব্যবহার করা হয়েছে
url = "https://raw.githubusercontent.com/campusx-official/100-days-of-machine-learning/a315efd557d2fc96984ded8f7f440af0320e6ae2/day15%20-%20working%20with%20csv%20files/test.csv"
header = {"User-Agent": "test"}

req = requests.get(url, headers=header)
data = StringIO(req.text)

# on_bad_lines='skip' ত্রুটিপূর্ণ লাইনগুলোকে এড়িয়ে যাবে
df = pd.read_csv(data, on_bad_lines='skip')

print(df.head())

   Unnamed: 0   Unnamed: 1 Unnamed: 2              Unnamed: 3 Unnamed: 4  \
0           0  enrollee_id       city  city_development_index     gender
1           1        29725    city_40                   0.776       Male
2           2        11561    city_21                   0.624        NaN
3           3        33241   city_115                   0.789        NaN
4           4          666   city_162                   0.767       Male

                Unnamed: 5           Unnamed: 6       Unnamed: 7  \
0      relevent_experience  enrolled_university  education_level
1   No relevent experience        no_enrollment         Graduate
2   No relevent experience     Full time course         Graduate
3   No relevent experience                  NaN         Graduate
4  Has relevent experience        no_enrollment          Masters

         Unnamed: 8  Unnamed: 9   Unnamed: 10     Unnamed: 11   Unnamed: 12  \
0  major_discipline  experience  company_size    company_type  last_new_job
1              STEM          15         50-99         Pvt Ltd            >4
2              STEM           5           NaN             NaN         never
3   Business Degree          <1           NaN         Pvt Ltd         never
4              STEM         >20         50-99  Funded Startup             4

      Unnamed: 13 Unnamed: 14
0  training_hours      target
1              47           0
2              83           0
3              52           1
4               8           0

In [5]:
pd.read_csv(r"C:\Users\DELL\Downloads\movie_titles_metadata.tsv",sep='\t',names=['sno','name','release_year','rating','votes','genres'])

,sno,name,release_year,rating,votes,genres
0,m0,10 things i hate about you,1999,6.9,62847.0,['comedy' 'romance']
1,m1,1492: conquest of paradise,1992,6.2,10421.0,['adventure' 'biography' 'drama' 'history']
2,m2,15 minutes,2001,6.1,25854.0,['action' 'crime' 'drama' 'thriller']
3,m3,2001: a space odyssey,1968,8.4,163227.0,['adventure' 'mystery' 'sci-fi']
4,m4,48 hrs.,1982,6.9,22289.0,['action' 'comedy' 'crime' 'drama' 'thriller']
...,...,...,...,...,...,...
612,m612,watchmen,2009,7.8,135229.0,['action' 'crime' 'fantasy' 'mystery' 'sci-fi'...
613,m613,xxx,2002,5.6,53505.0,['action' 'adventure' 'crime']
614,m614,x-men,2000,7.4,122149.0,['action' 'sci-fi']
615,m615,young frankenstein,1974,8.0,57618.0,['comedy' 'sci-fi']
616,m616,zulu dawn,1979,6.4,1911.0,['action' 'adventure' 'drama' 'history' 'war']

Header parameter

In [6]:
pd.read_csv(r"C:\Users\DELL\Downloads\test.csv",header=1)

,0,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0
1,2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0
2,3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1
3,4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0

In [7]:
pd.read_csv(r"C:\Users\DELL\Downloads\aug_train.csv",usecols=['enrollee_id','gender','education_level'])

       enrollee_id gender education_level
0             8949   Male        Graduate
1            29725   Male        Graduate
2            11561    NaN        Graduate
3            33241    NaN        Graduate
4              666   Male         Masters
...            ...    ...             ...
19153         7386   Male        Graduate
19154        31398   Male        Graduate
19155        24576   Male        Graduate
19156         5756   Male     High School
19157        23834    NaN  Primary School

[19158 rows x 3 columns]

In [8]:
pd.read_csv(r"C:\Users\DELL\Downloads\aug_train.csv",skiprows=[2,3])

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
2,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
3,21651,city_176,0.764,NaN,Has relevent experience,Part time course,Graduate,STEM,11,NaN,NaN,1,24,1.0
4,28806,city_160,0.920,Male,Has relevent experience,no_enrollment,High School,NaN,5,50-99,Funded Startup,1,24,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19151,7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,42,1.0
19152,31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,4,52,1.0
19153,24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,44,0.0
19154,5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,2,97,0.0
19155,23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2,NaN,NaN,1,127,0.0

In [9]:
pd.read_csv(r"C:\Users\DELL\Downloads\aug_train.csv",nrows=100)

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,12081,city_65,0.802,Male,Has relevent experience,Full time course,Graduate,STEM,9,50-99,Pvt Ltd,1,33,0.0
96,7364,city_160,0.920,NaN,No relevent experience,Full time course,High School,NaN,2,100-500,Pvt Ltd,1,142,0.0
97,11184,city_74,0.579,NaN,No relevent experience,Full time course,Graduate,STEM,2,100-500,Pvt Ltd,1,34,0.0
98,7016,city_65,0.802,Male,Has relevent experience,no_enrollment,Graduate,STEM,6,50-99,Pvt Ltd,2,14,1.0
99,8695,city_11,0.550,Male,Has relevent experience,no_enrollment,Graduate,STEM,6,10/49,Pvt Ltd,2,27,1.0

Encoding parameter

In [10]:
pd.read_csv(r"C:\Users\DELL\Downloads\zomato.csv",encoding='latin-1')

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9546,5915730,NamlÛ± Gurme,208,ÛÁstanbul,"Kemankeô Karamustafa Paôa Mahallesi, RÛ±htÛ±...",Karakí_y,"Karakí_y, ÛÁstanbul",28.977392,41.022793,Turkish,...,Turkish Lira(TL),No,No,No,No,3,4.1,Green,Very Good,788
9547,5908749,Ceviz AÛôacÛ±,208,ÛÁstanbul,"Koôuyolu Mahallesi, Muhittin íìstí_ndaÛô Cadd...",Koôuyolu,"Koôuyolu, ÛÁstanbul",29.041297,41.009847,"World Cuisine, Patisserie, Cafe",...,Turkish Lira(TL),No,No,No,No,3,4.2,Green,Very Good,1034
9548,5915807,Huqqa,208,ÛÁstanbul,"Kuruí_eôme Mahallesi, Muallim Naci Caddesi, N...",Kuruí_eôme,"Kuruí_eôme, ÛÁstanbul",29.034640,41.055817,"Italian, World Cuisine",...,Turkish Lira(TL),No,No,No,No,4,3.7,Yellow,Good,661
9549,5916112,Aôôk Kahve,208,ÛÁstanbul,"Kuruí_eôme Mahallesi, Muallim Naci Caddesi, N...",Kuruí_eôme,"Kuruí_eôme, ÛÁstanbul",29.036019,41.057979,Restaurant Cafe,...,Turkish Lira(TL),No,No,No,No,4,4.0,Green,Very Good,901
9550,5927402,Walter's Coffee Roastery,208,ÛÁstanbul,"CafeaÛôa Mahallesi, BademaltÛ± Sokak, No 21/B,...",Moda,"Moda, ÛÁstanbul",29.026016,40.984776,Cafe,...,Turkish Lira(TL),No,No,No,No,2,4.0,Green,Very Good,591

In [11]:
pd.read_csv(r"C:\Users\DELL\Downloads\aug_train.csv").info()

<class 'pandas.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   enrollee_id             19158 non-null  int64
 1   city                    19158 non-null  str
 2   city_development_index  19158 non-null  float64
 3   gender                  14650 non-null  str
 4   relevent_experience     19158 non-null  str
 5   enrolled_university     18772 non-null  str
 6   education_level         18698 non-null  str
 7   major_discipline        16345 non-null  str
 8   experience              19093 non-null  str
 9   company_size            13220 non-null  str
 10  company_type            13018 non-null  str
 11  last_new_job            18735 non-null  str
 12  training_hours          19158 non-null  int64
 13  target                  19158 non-null  float64
dtypes: float64(2), int64(2), str(10)
memory usage: 2.0 MB

In [12]:
pd.read_csv(r"C:\Users\DELL\Downloads\aug_train.csv",dtype={'target':int}).info()

<class 'pandas.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   enrollee_id             19158 non-null  int64
 1   city                    19158 non-null  str
 2   city_development_index  19158 non-null  float64
 3   gender                  14650 non-null  str
 4   relevent_experience     19158 non-null  str
 5   enrolled_university     18772 non-null  str
 6   education_level         18698 non-null  str
 7   major_discipline        16345 non-null  str
 8   experience              19093 non-null  str
 9   company_size            13220 non-null  str
 10  company_type            13018 non-null  str
 11  last_new_job            18735 non-null  str
 12  training_hours          19158 non-null  int64
 13  target                  19158 non-null  int64
dtypes: float64(1), int64(3), str(10)
memory usage: 2.0 MB

Handling Dates

In [13]:
pd.read_csv(r"C:\Users\DELL\Downloads\IPL Matches 2008-2020.csv").info()

<class 'pandas.DataFrame'>
RangeIndex: 816 entries, 0 to 815
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               816 non-null    int64
 1   city             803 non-null    str
 2   date             816 non-null    str
 3   player_of_match  812 non-null    str
 4   venue            816 non-null    str
 5   neutral_venue    816 non-null    int64
 6   team1            816 non-null    str
 7   team2            816 non-null    str
 8   toss_winner      816 non-null    str
 9   toss_decision    816 non-null    str
 10  winner           812 non-null    str
 11  result           812 non-null    str
 12  result_margin    799 non-null    float64
 13  eliminator       812 non-null    str
 14  method           19 non-null     str
 15  umpire1          816 non-null    str
 16  umpire2          816 non-null    str
dtypes: float64(1), int64(2), str(14)
memory usage: 108.5 KB

In [14]:
pd.read_csv(r"C:\Users\DELL\Downloads\IPL Matches 2008-2020.csv").info()

<class 'pandas.DataFrame'>
RangeIndex: 816 entries, 0 to 815
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               816 non-null    int64
 1   city             803 non-null    str
 2   date             816 non-null    str
 3   player_of_match  812 non-null    str
 4   venue            816 non-null    str
 5   neutral_venue    816 non-null    int64
 6   team1            816 non-null    str
 7   team2            816 non-null    str
 8   toss_winner      816 non-null    str
 9   toss_decision    816 non-null    str
 10  winner           812 non-null    str
 11  result           812 non-null    str
 12  result_margin    799 non-null    float64
 13  eliminator       812 non-null    str
 14  method           19 non-null     str
 15  umpire1          816 non-null    str
 16  umpire2          816 non-null    str
dtypes: float64(1), int64(2), str(14)
memory usage: 108.5 KB

In [15]:
pd.read_csv(r"C:\Users\DELL\Downloads\IPL Matches 2008-2020.csv",parse_dates=['date']).info()

<class 'pandas.DataFrame'>
RangeIndex: 816 entries, 0 to 815
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               816 non-null    int64
 1   city             803 non-null    str
 2   date             816 non-null    datetime64[us]
 3   player_of_match  812 non-null    str
 4   venue            816 non-null    str
 5   neutral_venue    816 non-null    int64
 6   team1            816 non-null    str
 7   team2            816 non-null    str
 8   toss_winner      816 non-null    str
 9   toss_decision    816 non-null    str
 10  winner           812 non-null    str
 11  result           812 non-null    str
 12  result_margin    799 non-null    float64
 13  eliminator       812 non-null    str
 14  method           19 non-null     str
 15  umpire1          816 non-null    str
 16  umpire2          816 non-null    str
dtypes: datetime64[us](1), float64(1), int64(2), str(13)
memory usage: 108.5 KB

Convertors

In [17]:
pd.read_csv(r"C:\Users\DELL\Downloads\IPL Matches 2008-2020.csv").head()

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
0,335982,Bangalore,2008-04-18,BB McCullum,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,NaN,MR Benson,SL Shastri
2,335984,Delhi,2008-04-19,MF Maharoof,Feroz Shah Kotla,0,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,Mumbai,2008-04-20,MV Boucher,Wankhede Stadium,0,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,N,NaN,SJ Davis,DJ Harper
4,335986,Kolkata,2008-04-20,DJ Hussey,Eden Gardens,0,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,N,NaN,BF Bowden,K Hariharan

In [18]:
def rename(name):
    if name == 'Royal Challengers Bangalore':
        return 'RCB'
    else:
        return name

In [19]:
rename("Royal Challengers Bangalore")

'RCB'

In [20]:
pd.read_csv(r"C:\Users\DELL\Downloads\IPL Matches 2008-2020.csv",converters={'team1':rename})

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
0,335982,Bangalore,2008-04-18,BB McCullum,M Chinnaswamy Stadium,0,RCB,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,NaN,MR Benson,SL Shastri
2,335984,Delhi,2008-04-19,MF Maharoof,Feroz Shah Kotla,0,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,Mumbai,2008-04-20,MV Boucher,Wankhede Stadium,0,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,N,NaN,SJ Davis,DJ Harper
4,335986,Kolkata,2008-04-20,DJ Hussey,Eden Gardens,0,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,N,NaN,BF Bowden,K Hariharan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
811,1216547,Dubai,2020-09-28,AB de Villiers,Dubai International Cricket Stadium,0,RCB,Mumbai Indians,Mumbai Indians,field,Royal Challengers Bangalore,tie,NaN,Y,NaN,Nitin Menon,PR Reiffel
812,1237177,Dubai,2020-11-05,JJ Bumrah,Dubai International Cricket Stadium,0,Mumbai Indians,Delhi Capitals,Delhi Capitals,field,Mumbai Indians,runs,57.0,N,NaN,CB Gaffaney,Nitin Menon
813,1237178,Abu Dhabi,2020-11-06,KS Williamson,Sheikh Zayed Stadium,0,RCB,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,wickets,6.0,N,NaN,PR Reiffel,S Ravi
814,1237180,Abu Dhabi,2020-11-08,MP Stoinis,Sheikh Zayed Stadium,0,Delhi Capitals,Sunrisers Hyderabad,Delhi Capitals,bat,Delhi Capitals,runs,17.0,N,NaN,PR Reiffel,S Ravi
815,1237181,Dubai,2020-11-10,TA Boult,Dubai International Cricket Stadium,0,Delhi Capitals,Mumbai Indians,Delhi Capitals,bat,Mumbai Indians,wickets,5.0,N,NaN,CB Gaffaney,Nitin Menon

na_values parameter

if there is hypan or something than teat as missing value

In [22]:
pd.read_csv(r"C:\Users\DELL\Downloads\aug_train.csv",na_values=['-'])

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19153,7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,42,1.0
19154,31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,4,52,1.0
19155,24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,44,0.0
19156,5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,2,97,0.0
19157,23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2,NaN,NaN,1,127,0.0

Loading huge dataset in chunks

In [28]:
df=pd.read_csv(r"C:\Users\DELL\Downloads\aug_train.csv",chunksize=1000)

In [29]:
for chunk in df:
    print(chunk.shape)

(1000, 14)
(1000, 14)
(1000, 14)
(1000, 14)
(1000, 14)
(1000, 14)
(1000, 14)
(1000, 14)
(1000, 14)
(1000, 14)
(1000, 14)
(1000, 14)
(1000, 14)
(1000, 14)
(1000, 14)
(1000, 14)
(1000, 14)
(1000, 14)
(1000, 14)
(158, 14)

Import xcel file

In [32]:
%pip install openpyxl

Collecting openpyxl
  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Using cached et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Using cached et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

In [33]:
pd.read_excel(r"C:\Users\DELL\Downloads\Project-Management-Sample-Data.xlsx")

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,NaN,Excel Sample Data,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Project Management Data,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,Project Name,Task Name,Assigned to,Start Date,Days Required,End Date,Progress
5,NaN,Marketing,Market Research,Alice,2024-01-01 00:00:00,13,2024-01-14 00:00:00,0.78
6,NaN,Marketing,Content Creation,Bob,2024-01-14 00:00:00,14,2024-01-28 00:00:00,1
7,NaN,Marketing,Social Media Planning,Charlie,2024-01-28 00:00:00,22,2024-02-19 00:00:00,0.45
8,NaN,Marketing,Campaign Analysis,Daisy,2024-02-18 00:00:00,25,2024-03-14 00:00:00,0
9,NaN,Product Dev,Prototype Development,Ethan,2024-01-02 00:00:00,18,2024-01-20 00:00:00,1
10,NaN,Product Dev,Quality Assurance,Fiona,2024-01-20 00:00:00,10,2024-01-30 00:00:00,0.78
11,NaN,Product Dev,User Interface Design,Gabriel,2024-02-04 00:00:00,25,2024-02-29 00:00:00,0
12,NaN,Customer Svc,Service Improvement,Hannah,2024-02-01 00:00:00,22,2024-02-23 00:00:00,1
13,NaN,Customer Svc,Ticket Resolution,Ian,2024-02-24 00:00:00,25,2024-03-20 00:00:00,1
14,NaN,Customer Svc,Customer Feedback,Julia,2024-03-21 00:00:00,30,2024-04-20 00:00:00,0
15,NaN,Financial,Budget Analysis,Kevin,2024-02-02 00:00:00,22,2024-02-24 00:00:00,0.1
16,NaN,Financial,Financial Reporting,Mark,2024-02-13 00:00:00,21,2024-02-09 00:00:00,0.78
17,NaN,Financial,Investment Planning,Mark,2024-03-19 00:00:00,25,2024-04-13 00:00:00,1
18,NaN,Research,Market Trends Analysis,Nathan,2024-01-02 00:00:00,23,2024-01-25 00:00:00,0.5
19,NaN,Research,Data Collection,Olivia,2024-01-26 00:00:00,32,2024-02-27 00:00:00,0
20,NaN,Research,Research Paper Writing,Peter,2024-02-28 00:00:00,27,2024-03-26 00:00:00,0
21,NaN,Development,Software Development,Quinn,2024-01-02 00:00:00,36,2024-02-07 00:00:00,1
22,NaN,Development,Feature Enhancement,Rachel,2024-02-08 00:00:00,34,2024-03-13 00:00:00,0
23,NaN,Development,Code Review,Sam,2024-03-14 00:00:00,30,2024-04-13 00:00:00,0
24,NaN,Production,Manufacturing,Tim,2024-01-03 00:00:00,47,2024-02-19 00:00:00,0.3
25,NaN,Production,Quality Control,Ursula,2024-02-17 00:00:00,27,2024-03-15 00:00:00,0
26,NaN,Production,Packaging Design,Victor,2024-03-14 00:00:00,22,2024-04-05 00:00:00,0
27,NaN,Sales,Lead Generation,Wendy,2024-01-03 00:00:00,60,2024-03-03 00:00:00,0.7
28,NaN,Sales,Client Meetings,Xavier,2024-01-06 00:00:00,20,2024-01-26 00:00:00,0.78
29,NaN,Sales,Contract Negotiation,Yvette,2024-02-03 00:00:00,35,2024-03-09 00:00:00,0
30,NaN,Support,Technical Support,Zoe,2024-01-01 00:00:00,25,2024-01-26 00:00:00,1
31,NaN,Support,Bug Fixes,Aaron,2024-01-27 00:00:00,31,2024-02-27 00:00:00,1
32,NaN,Support,Software Updates,Bella,2024-03-02 00:00:00,22,2024-03-24 00:00:00,0
33,NaN,Operations,Process Optimization,Calvin,2024-01-03 00:00:00,30,2024-02-02 00:00:00,0.4
34,NaN,Operations,Inventory Management,Diane,2024-02-03 00:00:00,25,2024-02-28 00:00:00,0
35,NaN,Operations,Facility Maintenance,Edward,2024-02-29 00:00:00,20,2024-03-20 00:00:00,0
36,NaN,Consulting,Strategic Planning,Fiona,2024-01-02 00:00:00,35,2024-02-06 00:00:00,0.6
37,NaN,Consulting,Market Expansion,Gary,2024-02-02 00:00:00,32,2024-03-05 00:00:00,0
38,NaN,Consulting,Client Advisory,Helen,2024-03-06 00:00:00,25,2024-03-31 00:00:00,0
39,NaN,Training,Employee Training,Isaac,2024-01-04 00:00:00,27,2024-01-31 00:00:00,0.8
40,NaN,Training,Certification Programs,Jane,2024-01-28 00:00:00,30,2024-02-27 00:00:00,0
41,NaN,Training,Skill Development,Kyle,2024-02-28 00:00:00,22,2024-03-21 00:00:00,0
42,NaN,Events,Event Planning,Laura,2024-01-03 00:00:00,25,2024-01-28 00:00:00,0.3
43,NaN,Events,Conference Management,Mike,2024-02-03 00:00:00,20,2024-02-23 00:00:00,0
44,NaN,Events,Sponsorship Coordinatio,n Nancy,2024-02-24 00:00:00,35,2024-03-30 00:00:00,0
45,NaN,Logistics,Supply Chain Management,Oscar,2024-01-03 00:00:00,25,2024-01-28 00:00:00,0.5
46,NaN,Logistics,Transportation Planning,Patricia,2024-01-29 00:00:00,30,2024-02-28 00:00:00,1
47,NaN,Logistics,Inventory Optimization,Quentin,2024-03-29 00:00:00,20,2024-04-18 00:00:00,0
48,NaN,Engineering,Product Design,Rachel,2024-01-02 00:00:00,25,2024-01-27 00:00:00,0.2
49,NaN,Engineering,System Integration,Sam,2024-02-02 00:00:00,22,2024-02-24 00:00:00,0
50,NaN,Engineering,Prototype Testing,Tom,2024-02-23 00:00:00,27,2024-03-21 00:00:00,0

Reading text file

In [35]:
pd.read_csv(r"C:\Users\DELL\Downloads\sample-1.txt",sep='\t')

                                     Sample Document
0  Fusce convallis metus id felis luctus adipisci...
1  Nulla facilisi. Phasellus accumsan cursus veli...
2  Praesent ac massa at ligula laoreet iaculis. P...
3  Pellentesque egestas, neque sit amet convallis...
4  In enim justo, rhoncus ut, imperdiet a, venena...