plotly-"Next Level" ভিজ্যুয়ালাইজেশন লাইব্রেরি

plotly দিয়ে আমরা এমন গ্রাফ তৈরি করি যা Interactive—অর্থাৎ মাউস নাড়ালে ডেটা দেখা যায়, জুম করা যায় এবং ফিল্টার করা যায়।

Plotly Express (px): এটি নতুনদের জন্য। মাত্র এক লাইনে খুব সুন্দর গ্রাফ তৈরি করা যায়। (Seaborn-এর মতো সহজ)।

Plotly Graph Objects (go): এটি অ্যাডভান্স ইউজারদের জন্য। গ্রাফের প্রতিটি খুঁটিনাটি (কাস্টমাইজেশন) নিয়ন্ত্রণ করতে এটি ব্যবহার হয়।

Dash (The Power of Plotly)
আপনি যখন Plotly শিখবেন, তখন Dash সম্পর্কেও জানবেন। Dash ব্যবহার করে আপনি পাইথন দিয়েই পুরো একটি Web Dashboard বা অ্যাপ তৈরি করে ফেলতে পারেন, যেখানে কোনো HTML/CSS জানার প্রয়োজন নেই।

In [1]:
import pandas as pd
import numpy as np

In [3]:
import plotly.graph_objects as go
import plotly.express as px

In [4]:
#import dataset
irish=px.data.iris() 
tips=px.data.tips()

In [5]:
gap=px.data.gapminder()

In [6]:
gap.head()

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
0,Afghanistan,Asia,1952,28.801,8425333,779.445314,AFG,4
1,Afghanistan,Asia,1957,30.332,9240934,820.853030,AFG,4
2,Afghanistan,Asia,1962,31.997,10267083,853.100710,AFG,4
3,Afghanistan,Asia,1967,34.020,11537966,836.197138,AFG,4
4,Afghanistan,Asia,1972,36.088,13079460,739.981106,AFG,4

plotly go

In [7]:
temp=gap[gap['year']==2007]
temp

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
11,Afghanistan,Asia,2007,43.828,31889923,974.580338,AFG,4
23,Albania,Europe,2007,76.423,3600523,5937.029526,ALB,8
35,Algeria,Africa,2007,72.301,33333216,6223.367465,DZA,12
47,Angola,Africa,2007,42.731,12420476,4797.231267,AGO,24
59,Argentina,Americas,2007,75.320,40301927,12779.379640,ARG,32
...,...,...,...,...,...,...,...,...
1655,Vietnam,Asia,2007,74.249,85262356,2441.576404,VNM,704
1667,West Bank and Gaza,Asia,2007,73.422,4018332,3025.349798,PSE,275
1679,"Yemen, Rep.",Asia,2007,62.698,22211743,2280.769906,YEM,887
1691,Zambia,Africa,2007,42.384,11746035,1271.211593,ZMB,894
1703,Zimbabwe,Africa,2007,43.487,12311143,469.709298,ZWE,716

In [8]:
import plotly.io as pio
pio.renderers.default = 'browser'  # Stable in VS Code/Jupyter without mime renderer issues

In [9]:
import sys
!{sys.executable} -m pip install --upgrade nbformat

Requirement already satisfied: nbformat in d:\code\.venv\Lib\site-packages (5.10.4)
Requirement already satisfied: fastjsonschema>=2.15 in d:\code\.venv\Lib\site-packages (from nbformat) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in d:\code\.venv\Lib\site-packages (from nbformat) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in d:\code\.venv\Lib\site-packages (from nbformat) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in d:\code\.venv\Lib\site-packages (from nbformat) (5.14.3)
Requirement already satisfied: attrs>=22.2.0 in d:\code\.venv\Lib\site-packages (from jsonschema>=2.6->nbformat) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in d:\code\.venv\Lib\site-packages (from jsonschema>=2.6->nbformat) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in d:\code\.venv\Lib\site-packages (from jsonschema>=2.6->nbformat) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in d:\code\.venv\Lib\site-packages (from jsonschema>=2.6->nbformat) (0.30.0)
Requirement already satisfied: platformdirs>=2.5 in d:\code\.venv\Lib\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat) (4.9.2)

In [10]:
import nbformat
print(nbformat.__version__)

5.10.4

In [10]:
trace1=go.Scatter(x=temp['lifeExp'],y=temp['gdpPercap'])
data=[trace1] #list
layout=go.Layout(title='life exp vs gdp per capital for 2007',xaxis={'title':'life exp'},yaxis={'title':'gpd'})
fig=go.Figure(data,layout)
fig.show(renderer='browser')

In [11]:
trace1=go.Scatter(x=temp['lifeExp'],y=temp['gdpPercap'],mode='markers')
data=[trace1] #list
layout=go.Layout(title='life exp vs gdp per capital for 2007',xaxis={'title':'life exp'},yaxis={'title':'gpd'})
fig=go.Figure(data,layout)
fig.show(renderer='browser')

In [12]:
trace1=go.Scatter(x=temp['lifeExp'],y=temp['gdpPercap'])
trace2=go.Scatter(x=[0,1,2],y=[0,90,30000],mode='lines')
data=[trace1,trace2] #list
layout=go.Layout(title='life exp vs gdp per capital for 2007',xaxis={'title':'life exp'},yaxis={'title':'gpd'})
fig=go.Figure(data,layout)
fig.show(renderer='browser')

plotly express

যেখানে go.Scatter ব্যবহার করতে অনেক লাইন লাগে, px.scatter সেটি এক লাইনেই করে দেয়।

In [11]:
temp.head()

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
11,Afghanistan,Asia,2007,43.828,31889923,974.580338,AFG,4
23,Albania,Europe,2007,76.423,3600523,5937.029526,ALB,8
35,Algeria,Africa,2007,72.301,33333216,6223.367465,DZA,12
47,Angola,Africa,2007,42.731,12420476,4797.231267,AGO,24
59,Argentina,Americas,2007,75.320,40301927,12779.379640,ARG,32

In [30]:
px.scatter(temp,x='lifeExp',y='gdpPercap')

In [31]:
px.scatter(temp,x='lifeExp',y='gdpPercap',color='continent')

In [32]:
px.scatter(temp,x='lifeExp',y='gdpPercap',color='continent',size='pop',size_max=50)

In [33]:
px.scatter(temp,x='lifeExp',y='gdpPercap',color='continent',size='pop',size_max=50,hover_name='country')

In [34]:
px.scatter(gap,x='lifeExp',y='gdpPercap',
           color='continent',size='pop',
           size_max=50,hover_name='country',
           animation_frame='year',animation_group='country')

In [35]:
px.scatter(gap,x='lifeExp',y='gdpPercap',
           color='continent',size='pop',
           size_max=50,hover_name='country',
           range_x=[30,85],
           animation_frame='year',animation_group='country')

In [12]:
#line plot
ban=gap[gap['country']=='Bangladesh']
ban.head()

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
96,Bangladesh,Asia,1952,37.484,46886859,684.244172,BGD,50
97,Bangladesh,Asia,1957,39.348,51365468,661.637458,BGD,50
98,Bangladesh,Asia,1962,41.216,56839289,686.341554,BGD,50
99,Bangladesh,Asia,1967,43.453,62821884,721.186086,BGD,50
100,Bangladesh,Asia,1972,45.252,70759295,630.233627,BGD,50

In [39]:
px.line(ban,x='year',y='pop',title='Bangladesh pop growth')

In [13]:
#plot india ban pk line plot
trio=gap[gap['country'].isin(['India','Bangladesh','Pakistan'])].pivot(index='year',columns='country',values='lifeExp')

In [14]:
trio

country  Bangladesh   India  Pakistan
year
1952         37.484  37.373    43.436
1957         39.348  40.249    45.557
1962         41.216  43.605    47.670
1967         43.453  47.193    49.800
1972         45.252  50.651    51.929
1977         46.923  54.208    54.043
1982         50.009  56.596    56.158
1987         52.819  58.553    58.245
1992         56.018  60.223    60.838
1997         59.412  61.765    61.818
2002         62.013  62.879    63.610
2007         64.062  64.698    65.483

In [43]:
px.line(trio,x=trio.index,y=trio.columns)

In [15]:
ban.head()

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
96,Bangladesh,Asia,1952,37.484,46886859,684.244172,BGD,50
97,Bangladesh,Asia,1957,39.348,51365468,661.637458,BGD,50
98,Bangladesh,Asia,1962,41.216,56839289,686.341554,BGD,50
99,Bangladesh,Asia,1967,43.453,62821884,721.186086,BGD,50
100,Bangladesh,Asia,1972,45.252,70759295,630.233627,BGD,50

In [16]:
#plot india ban pk line plot
trio=gap[gap['country'].isin(['India','Bangladesh','Pakistan'])].pivot(index='year',columns='country',values='gdpPercap')

In [17]:
trio.head()

country  Bangladesh       India     Pakistan
year
1952     684.244172  546.565749   684.597144
1957     661.637458  590.061996   747.083529
1962     686.341554  658.347151   803.342742
1967     721.186086  700.770611   942.408259
1972     630.233627  724.032527  1049.938981

In [47]:
px.bar(trio,x=trio.index,y=trio.columns,barmode='group')

In [48]:
px.bar(trio,x=trio.index,y=trio.columns,barmode='group',log_y=True,text_auto=True)

In [18]:
#plot india ban pk line plot
trio=gap[gap['country'].isin(['India','Bangladesh','Pakistan'])].pivot(index='year',columns='country',values='pop')

In [19]:
trio.head()

country  Bangladesh      India  Pakistan
year
1952       46886859  372000000  41346560
1957       51365468  409000000  46679944
1962       56839289  454000000  53100671
1967       62821884  506000000  60641899
1972       70759295  567000000  69325921

In [54]:
px.bar(trio,x=trio.index,y=trio.columns,barmode='group',text_auto=True,log_y=True)

In [24]:
px.bar(trio,x=trio.index,y=trio.columns,text_auto=True,log_y=True)

# stackred bar chat

In [22]:
temp=gap[gap['year']==2007]
temp.head()

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
11,Afghanistan,Asia,2007,43.828,31889923,974.580338,AFG,4
23,Albania,Europe,2007,76.423,3600523,5937.029526,ALB,8
35,Algeria,Africa,2007,72.301,33333216,6223.367465,DZA,12
47,Angola,Africa,2007,42.731,12420476,4797.231267,AGO,24
59,Argentina,Americas,2007,75.320,40301927,12779.379640,ARG,32

In [25]:
px.bar(temp,x='continent',y='pop',color='country',log_y=True)

In [27]:
#bar chat animation
px.bar(gap,x='continent',y='pop',color='continent',log_y=True,animation_frame='year',animation_group='country')

Race bar chat

In [31]:
#bar chat animation
px.bar(gap,x='continent',y='pop',color='continent',log_y=True,animation_frame='year',animation_group='country',range_y=[10**5, 10**10])

In [33]:
#histogram
temp=gap[gap['year']==2007]

In [34]:
temp.head()

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
11,Afghanistan,Asia,2007,43.828,31889923,974.580338,AFG,4
23,Albania,Europe,2007,76.423,3600523,5937.029526,ALB,8
35,Algeria,Africa,2007,72.301,33333216,6223.367465,DZA,12
47,Angola,Africa,2007,42.731,12420476,4797.231267,AGO,24
59,Argentina,Americas,2007,75.320,40301927,12779.379640,ARG,32

In [41]:
px.histogram(temp,x='lifeExp',color='continent',nbins=30,text_auto=True)

In [43]:
px.histogram(temp,x='lifeExp',color='continent',nbins=30,text_auto=True)

In [47]:
irish.head()

   sepal_length  sepal_width  petal_length  petal_width species  species_id
0           5.1          3.5           1.4          0.2  setosa           1
1           4.9          3.0           1.4          0.2  setosa           1
2           4.7          3.2           1.3          0.2  setosa           1
3           4.6          3.1           1.5          0.2  setosa           1
4           5.0          3.6           1.4          0.2  setosa           1

In [46]:
px.histogram(irish,x='sepal_length',color='species',text_auto=True)

In [48]:
gap.head()

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
0,Afghanistan,Asia,1952,28.801,8425333,779.445314,AFG,4
1,Afghanistan,Asia,1957,30.332,9240934,820.853030,AFG,4
2,Afghanistan,Asia,1962,31.997,10267083,853.100710,AFG,4
3,Afghanistan,Asia,1967,34.020,11537966,836.197138,AFG,4
4,Afghanistan,Asia,1972,36.088,13079460,739.981106,AFG,4

In [54]:
EU=gap[(gap['year']==2007) & (gap['continent']=='Europe')]

In [55]:
EU.head()

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
23,Albania,Europe,2007,76.423,3600523,5937.029526,ALB,8
83,Austria,Europe,2007,79.829,8199783,36126.492700,AUT,40
119,Belgium,Europe,2007,79.441,10392226,33692.605080,BEL,56
155,Bosnia and Herzegovina,Europe,2007,74.852,4552198,7446.298803,BIH,70
191,Bulgaria,Europe,2007,73.005,7322858,10680.792820,BGR,100

In [ ]:
px.pie(EU,values='pop',names='country')

In [71]:
# pivot_table ব্যবহার করলে ডুপ্লিকেট ভ্যালুগুলো (যেমন এশিয়ার সব দেশ) যোগ হয়ে যাবে
result = gap[gap['year']==1952].pivot_table(index='continent', values='pop', aggfunc='sum').reset_index()


print(result)

  continent         pop
0    Africa   237640501
1  Americas   345152446
2      Asia  1395357351
3    Europe   418120846
4   Oceania    10686006

In [73]:
px.pie(result,values='pop',names='continent')

Sunburst

In [74]:
temp.head()

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
11,Afghanistan,Asia,2007,43.828,31889923,974.580338,AFG,4
23,Albania,Europe,2007,76.423,3600523,5937.029526,ALB,8
35,Algeria,Africa,2007,72.301,33333216,6223.367465,DZA,12
47,Angola,Africa,2007,42.731,12420476,4797.231267,AGO,24
59,Argentina,Americas,2007,75.320,40301927,12779.379640,ARG,32

In [75]:
px.sunburst(temp,path=['continent','country'],values='pop')

In [76]:
px.sunburst(temp,path=['continent','country'],values='pop',color='lifeExp')

In [77]:
tips.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
px.sunburst(tips,path=['sex','smoker','day'],values='total_bill',color='size')

Treemap

In [79]:
px.treemap(temp,path=[px.Constant('World'),'continent','country'],values='pop',color='lifeExp')

Heatmap

In [ ]:
tips.head()

In [ ]:
tips.pivot_table(index='day',columns='sex',values='total_bill',aggfunc='sum')

3D

In [ ]:
px.scatter_3d(temp,x='lifeExp',y='pop',z='gdpPercap',log_y=True,color='contrinent')